require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Rails/RakeEnvironment:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
