language: ruby
rvm:
  - 2.7.0
cache:
  - bundler
  - yarn
services:
  - docker
before_install:
  - docker pull postgres:13.2
  - docker run -d -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=root postgres:13.2
  - nvm install
before_script:
  - bundle --jobs=3 --retry=3
  - yarn
  - bundle exec rails db:create
  - bundle exec rails db:migrate
script:
  - yarn eslint
  - bundle exec rubocop
  - bundle exec rspec
  - yarn test
